#!/usr/bin/env python3
"""Prepare clean MG5 project copies for fresh Expansion-drive production."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path

from write_mg5_beam_configs import DEFAULT_PROJECTS, polbeam2


EXCLUDES = (
    "Events",
    "HTML",
    "full_me",
    "decay_me",
    "*.log",
    "MG5_debug",
    "ME5_debug",
    "results.dat",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, default=Path("/media/higinio/Expansion1/Madgraph"))
    parser.add_argument("--fresh-root", type=Path, default=Path("/media/higinio/Expansion1/MadgraphFresh"))
    parser.add_argument("--out-dir", type=Path, default=Path("JHEP_Revised/config/madgraph_runs_fresh"))
    parser.add_argument("--scenario", choices=["isronlyll", "clic3000ll"], default="clic3000ll")
    parser.add_argument("--nevents", type=int, default=10000)
    parser.add_argument("--seed", type=int, default=20260529)
    parser.add_argument("--project", action="append", default=[], help="Project name to prepare. Can be repeated.")
    parser.add_argument("--overwrite", action="store_true", help="Delete existing fresh project before copying.")
    return parser.parse_args()


def safe_name(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", text)


def command_text(project_dir: Path, scenario: str, nevents: int, seed: int, pol2: float) -> str:
    run_name = f"{scenario}_nev{nevents}_fresh"
    return f"""# Auto-generated by JHEP_Revised/tools/prepare_fresh_mg5_projects.py
launch {project_dir} -n {run_name}
set nevents {nevents}
set iseed {seed}
set ebeam1 1500.0
set ebeam2 1500.0
set lpp1 -3
set lpp2 3
set pdlabel1 {scenario}
set pdlabel2 {scenario}
set lhaid 0
set polbeam1 0.0
set polbeam2 {pol2:.1f}
done
"""


def run_rsync(source: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["rsync", "-a", "--delete"]
    for pattern in EXCLUDES:
        cmd.append(f"--exclude={pattern}")
    cmd.extend([f"{source}/", f"{dest}/"])
    subprocess.run(cmd, check=True)
    (dest / "Events").mkdir(exist_ok=True)
    (dest / "HTML").mkdir(exist_ok=True)


def main() -> None:
    args = parse_args()
    projects = args.project or DEFAULT_PROJECTS
    args.out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for project in projects:
        source = args.source_root / project
        if not source.exists():
            print(f"[skip] missing source: {source}")
            continue
        dest = args.fresh_root / f"{safe_name(project)}_fresh"
        if dest.exists() and args.overwrite:
            shutil.rmtree(dest)
        run_rsync(source, dest)
        card = args.out_dir / f"{safe_name(project)}_{args.scenario}_nev{args.nevents}_fresh.mg5"
        card.write_text(command_text(dest, args.scenario, args.nevents, args.seed, polbeam2(project)), encoding="utf-8")
        written.append(card)
        print(f"[ready] {project} -> {dest}")
    print(f"wrote {len(written)} MG5 command files in {args.out_dir}")


if __name__ == "__main__":
    main()
