#!/usr/bin/env python3
"""Write MG5 launch command files for beam-spectrum comparison samples.

The existing ``*ISR`` MadGraph projects already contain the matrix element.
This tool writes reproducible command files that relaunch those projects with
the desired lepton-beam density:

* ``isronlyll`` for ISR-only.
* ``clic3000ll`` for ISR + CLIC 3 TeV luminosity spectrum/beamstrahlung.

The command files do not duplicate the generated process directories.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


DEFAULT_PROJECTS = [
    "Tt1200ISR",
    "Tt1200+80ISR",
    "Tt1200-80ISR",
    "Tt1600ISR",
    "Tt1600+80ISR",
    "Tt1600-80ISR",
    "Tt2000ISR",
    "Tt2000+80ISR",
    "Tt2000-80ISR",
    "Tt2400ISR",
    "Tt2400+80ISR",
    "Tt2400-80ISR",
    "ttbarISR",
    "ttbar+80ISR",
    "ttbar-80ISR",
    "ttzISR",
    "ttz+80ISR",
    "ttz-80ISR",
    "tthISR",
    "tth+80ISR",
    "tth-80ISR",
    "w+w-zISR",
    "w+w-z+80ISR",
    "w+w-z-80ISR",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--madgraph-root", type=Path, default=Path("/media/higinio/Expansion1/Madgraph"))
    parser.add_argument("--out-dir", type=Path, default=Path("JHEP_Revised/config/madgraph_runs"))
    parser.add_argument("--nevents", type=int, default=10000)
    parser.add_argument("--seed", type=int, default=20260528)
    parser.add_argument("--scenario", choices=["isronlyll", "clic3000ll"], default="isronlyll")
    parser.add_argument("--project", action="append", default=[], help="Project name under --madgraph-root. Can be repeated.")
    return parser.parse_args()


def polbeam2(project: str) -> float:
    if "+80" in project:
        return 80.0
    if "-80" in project:
        return -80.0
    return 0.0


def safe_name(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", text)


def command_text(project_dir: Path, scenario: str, nevents: int, seed: int, pol2: float) -> str:
    run_name = f"{scenario}_nev{nevents}"
    return f"""# Auto-generated by JHEP_Revised/tools/write_mg5_beam_configs.py
launch {project_dir} -n {run_name}
set nevents {nevents}
set iseed {seed}
set ebeam1 1500.0
set ebeam2 1500.0
set lpp1 -3
set lpp2 3
set pdlabel1 {scenario}
set pdlabel2 {scenario}
set lhaid 0
set polbeam1 0.0
set polbeam2 {pol2:.1f}
done
"""


def main() -> None:
    args = parse_args()
    projects = args.project or DEFAULT_PROJECTS
    args.out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for project in projects:
        project_dir = args.madgraph_root / project
        if not project_dir.exists():
            print(f"[skip] missing project: {project_dir}")
            continue
        path = args.out_dir / f"{safe_name(project)}_{args.scenario}_nev{args.nevents}.mg5"
        path.write_text(command_text(project_dir, args.scenario, args.nevents, args.seed, polbeam2(project)), encoding="utf-8")
        written.append(path)
    print(f"wrote {len(written)} MG5 command files in {args.out_dir}")
    for path in written[:8]:
        print(path)
    if len(written) > 8:
        print("...")


if __name__ == "__main__":
    main()
